version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
clone_depth: 10
build: off
artifacts:
- path: 'nginx.conf'
  name: TaskCat.Nginx
  type: zip
deploy:
- provider: Environment
  name: TaskCatDev
  on:
    branch: SelfHostService
- provider: Environment
  name: TaskCatProd
  on:
    branch: SelfHostServiceProd
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#builds'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#build'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true